In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from collections import Counter
import sklearn
from imblearn.under_sampling import RandomUnderSampler

In [2]:
%store -r fcc_relevant
data = fcc_relevant
data

is_sofw_dev  full_stack_wd  back_end_wd  front_end_wd  mobile_dev  \
0                0              0            0             0           0   
1                0              1            0             0           0   
2                0              0            0             0           0   
3                0              0            0             1           0   
4                0              0            0             0           0   
...            ...            ...          ...           ...         ...   
61086            0              0            0             0           0   
61087            1              0            0             0           0   
61089            0              0            0             0           0   
61090            0              0            0             1           1   
61091            0              1            1             1           0   

       devops  data_sc  qlty_eng  ux_designer  prod_manager  ...  age  debt  \
0           0        1         0            0             0  ...   46     0   
1           0        1         0            0             0  ...   22     0   
2           0        1         0            0             0  ...   28     1   
3           0        1         0            0             0  ...   22     0   
4           0        1         0            0             0  ...   19     0   
...       ...      ...       ...          ...           ...  ...  ...   ...   
61086       0        0         0            0             0  ...   22     0   
61087       0        0         0            0             0  ...   28     0   
61089       0        0         0            0             0  ...   23     0   
61090       0        0         0            0             0  ...   30     0   
61091       1        1         1            1             0  ...   21     0   

       employment  youtube  online_resources  inperson_events  podcasts  \
0              -1        0                 2                1         0   
1               0        0                 6                0         0   
2               1        0                 2                0         0   
3               1        0                 3                0         1   
4               1        0                 4                1         0   
...           ...      ...               ...              ...       ...   
61086           0        0                 8                0         0   
61087           0        0                 2                0         0   
61089           0        2                 4                1         1   
61090          -1        0                 4                0         0   
61091          -1       12                18                0         1   

       gender_female  gender_male  gender_other  
0                  0            1             0  
1                  0            1             0  
2                  0            1             0  
3                  0            1             0  
4                  0            1             0  
...              ...          ...           ...  
61086              0            1             0  
61087              0            1             0  
61089              1            0             0  
61090              0            1             0  
61091              0            0             0  

[45374 rows x 27 columns]

In [6]:
X = data.drop(columns={'is_sofw_dev','full_stack_wd', 'back_end_wd', 'front_end_wd',
       'mobile_dev', 'devops', 'data_sc', 'qlty_eng', 'ux_designer',
       'prod_manager', 'game_dev', 'inf_security', 'data_eng', 'debt'})
y = data['is_sofw_dev']

In [7]:
X_column_names = list(X.columns)
X_column_names

['hours_learning_week',
 'months_programming',
 'attended_bootcamp',
 'coding_expenses',
 'age',
 'employment',
 'youtube',
 'online_resources',
 'inperson_events',
 'podcasts',
 'gender_female',
 'gender_male',
 'gender_other']

In [8]:
y_column_names = ['is_sofw_dev']
y_column_names

['is_sofw_dev']

In [9]:
rus = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(X, y)

In [10]:
print (X_resampled, y_resampled)

[[ 5  9  0 ...  0  1  0]
 [20  6  0 ...  0  1  0]
 [ 2 12  0 ...  1  0  0]
 ...
 [ 5 48  0 ...  0  1  0]
 [ 6 18  0 ...  0  1  0]
 [20 54  0 ...  0  1  0]] [0 0 0 ... 1 1 1]


In [12]:
print (sorted(Counter(y_resampled).items()))

[(0, 9839), (1, 9839)]


In [13]:
%store X_resampled
%store y_resampled

Stored 'X_resampled' (ndarray)
Stored 'y_resampled' (ndarray)


In [18]:
data_resampled_X = pd.DataFrame(X_resampled, columns=X_column_names)
data_resampled_y = pd.DataFrame(y_resampled, columns=y_column_names)
data_resampled = pd.concat([data_resampled_X, data_resampled_y], axis=1, sort=False)
data_resampled

hours_learning_week  months_programming  attended_bootcamp  \
0                        5                   9                  0   
1                       20                   6                  0   
2                        2                  12                  0   
3                        5                   0                  0   
4                       20                   6                  0   
...                    ...                 ...                ...   
19673                   30                  60                  0   
19674                   21                  24                  0   
19675                    5                  48                  0   
19676                    6                  18                  0   
19677                   20                  54                  0   

       coding_expenses  age  employment  youtube  online_resources  \
0                   25   34           1        0                 4   
1                  300   34           1        0                 5   
2                    0   34           1        0                 7   
3                    0   32           1        0                 2   
4                    0   43           0        0                 3   
...                ...  ...         ...      ...               ...   
19673              500   24           0        1                 4   
19674               25   31           1        1                 1   
19675                0   27           1        0                 3   
19676              500   22           1        2                 6   
19677              723   28           0        0                 2   

       inperson_events  podcasts  gender_female  gender_male  gender_other  \
0                    0         0              0            1             0   
1                    1         0              0            1             0   
2                    1         0              1            0             0   
3                    0         0              0            1             0   
4                    0         0              0            1             0   
...                ...       ...            ...          ...           ...   
19673                0         1              0            1             0   
19674                1         1              0            1             0   
19675                0         0              0            1             0   
19676                0         0              0            1             0   
19677                0         0              0            1             0   

       is_sofw_dev  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
19673            1  
19674            1  
19675            1  
19676            1  
19677            1  

[19678 rows x 14 columns]

In [19]:
%store data_resampled

Stored 'data_resampled' (DataFrame)
