In [1]:
import sklearn

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from collections import Counter
import sklearn
from imblearn.under_sampling import RandomUnderSampler

In [3]:
%store -r fcc_relevant
data = fcc_relevant
data

is_sofw_dev  full_stack_wd  back_end_wd  front_end_wd  mobile_dev  \
0                0              0            0             0           0   
1                0              1            0             0           0   
2                0              0            0             0           0   
3                0              0            0             1           0   
4                0              0            0             0           0   
5                0              0            0             0           0   
6                0              0            0             1           0   
7                0              1            0             0           0   
8                0              0            0             0           0   
9                1              0            0             0           0   
10               0              0            0             0           0   
11               1              0            0             0           0   
12               1              0            0             0           0   
13               0              0            0             0           0   
14               0              0            0             0           0   
16               0              0            0             0           0   
17               0              1            0             0           0   
18               0              0            0             0           0   
19               0              0            0             0           0   
20               0              0            0             0           0   
22               0              0            0             0           0   
23               0              0            0             0           0   
24               1              0            0             0           0   
25               0              0            0             0           0   
26               1              0            0             0           0   
27               0              0            0             0           0   
28               0              1            0             0           0   
29               0              0            0             0           0   
30               0              0            1             0           0   
31               1              0            0             0           0   
...            ...            ...          ...           ...         ...   
61052            0              0            0             1           0   
61053            1              0            0             0           0   
61054            0              0            0             0           0   
61055            0              0            0             0           0   
61056            0              0            0             0           0   
61057            0              0            1             1           0   
61058            0              0            0             0           0   
61059            0              0            0             0           0   
61061            0              0            0             0           1   
61062            0              0            0             0           0   
61063            0              1            0             0           0   
61064            0              0            1             0           0   
61065            1              0            0             0           0   
61066            0              0            0             0           0   
61068            0              0            0             0           0   
61072            0              0            0             0           0   
61073            0              0            0             1           0   
61077            0              0            0             0           0   
61078            0              0            0             0           0   
61079            0              0            0             0           0   
61080            0              0            0         

In [4]:
X = data.drop(columns={'is_sofw_dev','full_stack_wd', 'back_end_wd', 'front_end_wd',
       'mobile_dev', 'devops', 'data_sc', 'qlty_eng', 'ux_designer',
       'prod_manager', 'game_dev', 'inf_security', 'data_eng', 'debt'})
y = data['is_sofw_dev']

In [5]:
X_column_names = list(X.columns)
X_column_names

['hours_learning_week',
 'months_programming',
 'attended_bootcamp',
 'coding_expenses',
 'age',
 'employment',
 'youtube',
 'online_resources',
 'inperson_events',
 'podcasts',
 'gender_female',
 'gender_male',
 'gender_other']

In [6]:
y_column_names = ['is_sofw_dev']
y_column_names

['is_sofw_dev']

In [7]:
rus = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(X, y)

In [8]:
print (X_resampled, y_resampled)

[[ 5  9  0 ...  0  1  0]
 [20  6  0 ...  0  1  0]
 [ 2 12  0 ...  1  0  0]
 ...
 [ 5 48  0 ...  0  1  0]
 [ 6 18  0 ...  0  1  0]
 [20 54  0 ...  0  1  0]] [0 0 0 ... 1 1 1]


In [9]:
print (sorted(Counter(y_resampled).items()))

[(0, 9839), (1, 9839)]


In [10]:
%store X_resampled
%store y_resampled

Stored 'X_resampled' (ndarray)
Stored 'y_resampled' (ndarray)


In [11]:
data_resampled_X = pd.DataFrame(X_resampled, columns=X_column_names)
data_resampled_y = pd.DataFrame(y_resampled, columns=y_column_names)
data_resampled = pd.concat([data_resampled_X, data_resampled_y], axis=1, sort=False)
data_resampled

hours_learning_week  months_programming  attended_bootcamp  \
0                        5                   9                  0   
1                       20                   6                  0   
2                        2                  12                  0   
3                        5                   0                  0   
4                       20                   6                  0   
5                       30                   6                  1   
6                        0                   3                  0   
7                       50                  72                  0   
8                        7                  10                  0   
9                       20                   4                  1   
10                      20                   3                  0   
11                      25                  12                  0   
12                      10                   2                  0   
13                      10                   4                  0   
14                      25                   1                  0   
15                       5                  24                  0   
16                      30                   2                  0   
17                       5                  30                  0   
18                      20                   0                  0   
19                       5                   0                  0   
20                       5                   0                  0   
21                      18                   3                  0   
22                       0                   0                  0   
23                       7                   8                  0   
24                       4                   0                  0   
25                       3                  30                  0   
26                      10                  36                  0   
27                      35                  24                  0   
28                      40                   9                  0   
29                      20                  18                  0   
...                    ...                 ...                ...   
19648                    2                  60                  0   
19649                   10                   6                  1   
19650                    4                  12                  0   
19651                    7                  48                  0   
19652                    8                  23                  0   
19653                   20                  30                  0   
19654                    3                   3                  0   
19655                   30                  18                  0   
19656                   10                  84                  0   
19657                    4                   0                  0   
19658                    1                  60                  0   
19659                    6                  27                  0   
19660                    6                   1                  0   
19661                   40                  40                  0   
19662                   10                  32                  0   
19663                    6                  36                  0   
19664                    0                   0                  0   
19665                    4                  11                  0   
19666                    3                  24                  1   
19667                   21                  35                  0   
19668                   25                   4                  0   
19669                   16                   5                  0   
19670                    5                 108                  0   
19671                   10                  48                  0   
19672                   20                   6                  0   
19673                   30                  60                  0   
19674

In [12]:
%store data_resampled

Stored 'data_resampled' (DataFrame)
